import CPKHeXNative
import Foundation

/// A stat index into the IV/EV accessors: HP, Attack, Defense, Sp. Atk, Sp. Def, Speed.
public enum Stat: Int32, CaseIterable {
    case hp = 0, attack, defense, specialAttack, specialDefense, speed
}

/// Wraps a single Pokemon (box slot or party member) handle from PKHeX.Native.
public final class PKM {
    let handle: Int64

    init(handle: Int64) {
        self.handle = handle
    }

    deinit {
        pkhex_pkm_close(handle)
    }

    public var species: UInt16 {
        get { pkhex_pkm_get_species(handle) }
        set { pkhex_pkm_set_species(handle, newValue) }
    }

    /// Generation this entity's format belongs to (1-9).
    public var format: UInt8 { pkhex_pkm_get_format(handle) }

    public var level: UInt8 {
        get { pkhex_pkm_get_level(handle) }
        set { pkhex_pkm_set_level(handle, newValue) }
    }

    public var nature: UInt8 {
        get { pkhex_pkm_get_nature(handle) }
        set { pkhex_pkm_set_nature(handle, newValue) }
    }

    /// 0 = male, 1 = female, 2 = genderless.
    public var gender: UInt8 {
        get { pkhex_pkm_get_gender(handle) }
        set { pkhex_pkm_set_gender(handle, newValue) }
    }

    public func move(_ index: Int) -> UInt16 {
        pkhex_pkm_get_move(handle, Int32(index))
    }

    public func setMove(_ index: Int, to move: UInt16) {
        pkhex_pkm_set_move(handle, Int32(index), move)
    }

    public var moves: [UInt16] {
        (0..<4).map { move($0) }
    }

    /// Move IDs this Pokemon can currently legally learn (level-up, egg, TM/tutor, and moves from
    /// its recorded encounter/relearn set), for building a move picker. Does not include move ID 0
    /// ("None"); add that yourself as a placeholder for clearing a slot. Falls back to every move
    /// up to `maxMoveID` if legality analysis found no legal moves (e.g. malformed data).
    public var legalMoves: [UInt16] {
        let count = Int(pkhex_pkm_get_legal_move_count(handle))
        guard count > 0 else {
            return maxMoveID > 0 ? Array(1...maxMoveID) : []
        }
        return (0..<count).map { pkhex_pkm_get_legal_move(handle, Int32($0)) }
    }

    /// Highest move ID valid for this Pokemon's format.
    public var maxMoveID: UInt16 {
        pkhex_pkm_get_max_move_id(handle)
    }

    public func iv(_ stat: Stat) -> Int32 {
        pkhex_pkm_get_iv(handle, stat.rawValue)
    }

    public func setIV(_ stat: Stat, to value: Int32) {
        pkhex_pkm_set_iv(handle, stat.rawValue, value)
    }

    public func ev(_ stat: Stat) -> Int32 {
        pkhex_pkm_get_ev(handle, stat.rawValue)
    }

    public func setEV(_ stat: Stat, to value: Int32) {
        pkhex_pkm_set_ev(handle, stat.rawValue, value)
    }

    public var nickname: String {
        get { readNativeString { pkhex_pkm_get_nickname(handle, $0, $1) } }
        set { writeNativeString(newValue) { pkhex_pkm_set_nickname(handle, $0, $1) } }
    }

    /// Maximum nickname length for this Pokemon's generation/language.
    public var maxNicknameLength: Int { Int(pkhex_pkm_get_max_nickname_length(handle)) }

    /// Base file name (without extension) for this Pokemon's sprite, e.g. "b_25-1s".
    /// Matches image asset names generated by Scripts/generate_sprite_assets.py.
    public var spriteFileName: String {
        readNativeString { pkhex_pkm_get_sprite_file_name(handle, $0, $1) }
    }

    public var isLegal: Bool {
        pkhex_pkm_is_legal(handle) == 1
    }

    public func legalityReport(verbose: Bool = false) -> String {
        readNativeString { pkhex_pkm_get_legality_report(handle, $0, $1, verbose ? 1 : 0) }
    }

    /// Display name for this Pokemon's current species, e.g. "Totodile".
    public var speciesName: String {
        PokemonNames.species(species)
    }

    /// Display name for this Pokemon's current nature, e.g. "Adamant".
    public var natureName: String {
        PokemonNames.nature(nature)
    }

    /// Current PP remaining in the given move slot (0-3).
    public func movePP(_ index: Int) -> Int32 {
        pkhex_pkm_get_move_pp(handle, Int32(index))
    }

    /// Maximum PP (accounting for PP Ups) for the move currently in the given slot (0-3).
    public func movePPMax(_ index: Int) -> Int32 {
        pkhex_pkm_get_move_pp_max(handle, Int32(index))
    }
}

/// Display-name lookups for species/move/nature/item IDs, backed by PKHeX.Core's current-language
/// string tables. Independent of any PKM instance.
public enum PokemonNames {
    public static func species(_ id: UInt16) -> String {
        readNativeString { pkhex_species_get_name(id, $0, $1) }
    }

    public static func move(_ id: UInt16) -> String {
        readNativeString { pkhex_move_get_name(id, $0, $1) }
    }

    public static func nature(_ id: UInt8) -> String {
        readNativeString { pkhex_nature_get_name(id, $0, $1) }
    }

    public static func item(_ id: UInt16) -> String {
        readNativeString { pkhex_item_get_name(id, $0, $1) }
    }
}
