import CPKHeXNative
import Foundation

/// A stat index into the IV/EV accessors: HP, Attack, Defense, Sp. Atk, Sp. Def, Speed.
public enum Stat: Int32, CaseIterable {
    case hp = 0, attack, defense, specialAttack, specialDefense, speed
}

/// Wraps a single Pokemon (box slot or party member) handle from PKHeX.Native.
public final class PKM {
    let handle: Int64

    init(handle: Int64) {
        self.handle = handle
    }

    deinit {
        pkhex_pkm_close(handle)
    }

    public var species: UInt16 {
        get { pkhex_pkm_get_species(handle) }
        set { pkhex_pkm_set_species(handle, newValue) }
    }

    /// Generation this entity's format belongs to (1-9).
    public var format: UInt8 { pkhex_pkm_get_format(handle) }

    public var level: UInt8 {
        get { pkhex_pkm_get_level(handle) }
        set { pkhex_pkm_set_level(handle, newValue) }
    }

    public var nature: UInt8 {
        get { pkhex_pkm_get_nature(handle) }
        set { pkhex_pkm_set_nature(handle, newValue) }
    }

    /// 0 = male, 1 = female, 2 = genderless.
    public var gender: UInt8 {
        get { pkhex_pkm_get_gender(handle) }
        set { pkhex_pkm_set_gender(handle, newValue) }
    }

    public func move(_ index: Int) -> UInt16 {
        pkhex_pkm_get_move(handle, Int32(index))
    }

    public func setMove(_ index: Int, to move: UInt16) {
        pkhex_pkm_set_move(handle, Int32(index), move)
    }

    public var moves: [UInt16] {
        (0..<4).map { move($0) }
    }

    public func iv(_ stat: Stat) -> Int32 {
        pkhex_pkm_get_iv(handle, stat.rawValue)
    }

    public func setIV(_ stat: Stat, to value: Int32) {
        pkhex_pkm_set_iv(handle, stat.rawValue, value)
    }

    public func ev(_ stat: Stat) -> Int32 {
        pkhex_pkm_get_ev(handle, stat.rawValue)
    }

    public func setEV(_ stat: Stat, to value: Int32) {
        pkhex_pkm_set_ev(handle, stat.rawValue, value)
    }

    public var nickname: String {
        get { Self.readString(handle) { pkhex_pkm_get_nickname(handle, $0, $1) } }
        set {
            var utf16 = Array(newValue.utf16)
            pkhex_pkm_set_nickname(handle, &utf16, Int32(utf16.count))
        }
    }

    /// Base file name (without extension) for this Pokemon's sprite, e.g. "b_25-1s".
    /// Matches image asset names generated by Scripts/generate_sprite_assets.py.
    public var spriteFileName: String {
        Self.readString(handle) { pkhex_pkm_get_sprite_file_name(handle, $0, $1) }
    }

    public var isLegal: Bool {
        pkhex_pkm_is_legal(handle) == 1
    }

    public func legalityReport(verbose: Bool = false) -> String {
        Self.readString(handle) { pkhex_pkm_get_legality_report(handle, $0, $1, verbose ? 1 : 0) }
    }

    /// Calls a size-then-fill UTF-16 native accessor and decodes the result as a Swift String.
    private static func readString(_ handle: Int64, _ call: (UnsafeMutablePointer<UInt16>?, Int32) -> Int32) -> String {
        let requiredLength = call(nil, 0)
        guard requiredLength > 0 else { return "" }

        var buffer = [UInt16](repeating: 0, count: Int(requiredLength))
        let written = buffer.withUnsafeMutableBufferPointer { ptr in
            call(ptr.baseAddress, Int32(ptr.count))
        }
        guard written == requiredLength else { return "" }
        return String(utf16CodeUnits: buffer, count: buffer.count)
    }
}
